In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [12]:
a_list= [3.14, 2.17, 0, 1, 2]
converted_list = np.array(a_list, dtype=int)
print(converted_list)
print(f"array type: {converted_list.dtype}")

[3 2 0 1 2]
array type: int64


# Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.New Section

In [4]:
arr = np.arange(1,10).reshape(3,3)
print (arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.



In [7]:
np.random.seed(11)
random_arr = np.random.rand(4,5).round(2)
print(random_arr)

[[0.18 0.02 0.46 0.72 0.42]
 [0.49 0.01 0.49 0.94 0.85]
 [0.73 0.11 0.89 0.86 0.17]
 [0.63 0.02 0.12 0.32 0.16]]


# Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

In [ ]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [9]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1])

[20 21 22 23 24]


# Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [14]:
arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


# Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy

In [15]:
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Excercise 8: Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

In [17]:
arr = np.arange(10)

array_sum = np.sum(arr)
array_average = np.mean(arr)

print(f"Sum: {array_sum}")
print(f"Average: {array_average}")

Sum: 45
Average: 4.5


# Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [19]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

In [20]:
arr = np.arange(1,11)
print(arr[arr % 2 == 1])

[1 3 5 7 9]
